# Generated by Django 2.2.13 on 2021-06-04 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210604_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('fecha_emitida', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad_de_Medida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('fecha_emitida', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='products/images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Categoria')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Unidad_de_Medida')),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto')),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('sub_total', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto')),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('sub_total', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto')),
            ],
            options={
                'verbose_name': 'Model Base',
                'abstract': False,
            },
        ),
    ]
