# Generated by Django 2.2.13 on 2021-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria_compra_detalle_compra_detalle_venta_existencia_producto_unidad_de_medida_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencia',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
