# Generated by Django 2.2.13 on 2021-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(null=True, upload_to='products/images'),
        ),
    ]
