# Generated by Django 2.2.13 on 2021-06-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
